create database ADB1_N13_DATH#02
go
use ADB1_N13_DATH#02
go

CREATE TABLE LOAISANPHAM
(
	MALOAI VARCHAR(10) NOT NULL PRIMARY KEY,
	TENLOAI NVARCHAR(30) NOT NULL,
)
GO
CREATE TABLE SANPHAM
(
	MASP VARCHAR(10) NOT NULL PRIMARY KEY,
	TENSP NVARCHAR(50) NOT NULL,
	LOAISP VARCHAR(10) NOT NULL,
	GIA MONEY NOT NULL,
	DONVITINH NVARCHAR(20),
	MOTA NVARCHAR(200),
	SOLUONGTON INT NOT NULL,
	CONSTRAINT chk_slt CHECK(SOLUONGTON >= 0),
	FOREIGN KEY (LOAISP) REFERENCES LOAISANPHAM(MALOAI),
)
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) NOT NULL PRIMARY KEY,
	TENNV NVARCHAR(30) NOT NULL,
	SDT VARCHAR(10),
	DIACHI NVARCHAR(100),
	LOAINV NVARCHAR(30),
	LUONG MONEY,
	THUONG MONEY,
	DOANHSOBANHANG MONEY,
	DIEMDANH INT,
	CMND CHAR(12),
)
GO
 CREATE TABLE KHACHHANG
 (
	MAKH VARCHAR(10) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR(30) NOT NULL,
	SDT VARCHAR(10),
	DIACHI NVARCHAR(100),
	LOAIKH VARCHAR(10),
 )
 GO
 CREATE TABLE CHINHANH
 (
	MACN VARCHAR(10) NOT NULL PRIMARY KEY,
	DIACHICN NVARCHAR(100),
	SDTCN VARCHAR(10),
 )
 GO

 CREATE TABLE NHACUNGCAP
 (
	MANCC VARCHAR(10) NOT NULL PRIMARY KEY,
	TENNCC NVARCHAR(30) NOT NULL,
	DIACHI NVARCHAR(100),
	SDT VARCHAR(10),
 )
 GO

 CREATE TABLE DATHANG
 (
	MADATHANG VARCHAR(10) NOT NULL PRIMARY KEY,
	MANCC VARCHAR(10) NOT NULL,
	MACN VARCHAR(10) NOT NULL,
	FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
	FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN),
 )
GO
CREATE TABLE CTDATHANG
(
	MADATHANG VARCHAR(10) NOT NULL,
	MASP VARCHAR(10) NOT NULL,
	SOLUONGDAT INT NOT NULL,
	CONSTRAINT chk_sld CHECK(SOLUONGDAT >= 0),
	FOREIGN KEY (MADATHANG) REFERENCES DATHANG (MADATHANG),
	FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP),
	CONSTRAINT PK_CTDATHANG PRIMARY KEY (MADATHANG, MASP),
)
GO
 CREATE TABLE NHAPHANG
 (
	MANHAPHANG VARCHAR(10) NOT NULL PRIMARY KEY,
	MADATHANG VARCHAR(10) NOT NULL,
	MANCC VARCHAR(10) NOT NULL,
	MACN VARCHAR(10) NOT NULL,
	TONGTIENNHAP MONEY NOT NULL,
	FOREIGN KEY (MADATHANG) REFERENCES DATHANG (MADATHANG),
	FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP (MANCC),
	FOREIGN KEY (MACN) REFERENCES CHINHANH (MACN),
 )
 GO
 CREATE TABLE CTNHAPHANG
 (
	MANHAPHANG VARCHAR(10) NOT NULL,
	MASP VARCHAR(10) NOT NULL,
	SOLUONGNHAP INT NOT NULL,
	CONSTRAINT chk_sln CHECK(SOLUONGNHAP >= 0),
	GIATIEN MONEY NOT NULL,
	THANHTIEN MONEY NOT NULL,
	FOREIGN KEY (MANHAPHANG) REFERENCES NHAPHANG (MANHAPHANG),
	FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP),
	CONSTRAINT PK_CTNHAPHANG PRIMARY KEY (MANHAPHANG, MASP),
 )
 GO
 CREATE TABLE HOADONONLINE
 (
	MAHOADON VARCHAR(10) NOT NULL PRIMARY KEY,
	MAKH VARCHAR(10) NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	NGAYLAP DATE NOT NULL,
	DIACHIGIAOHANG NVARCHAR(100) NOT NULL,
	HINHTHUCTHANHTOAN NVARCHAR(30) NOT NULL,
	DONVIVANCHUYEN NVARCHAR(30) NOT NULL,
	PHIVANCHUYEN MONEY,
	TONGTIEN MONEY default 0,
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH),
 )
 GO
  CREATE TABLE CTHOADONONLINE
 (
	MAHOADON VARCHAR(10) NOT NULL,
	MASP VARCHAR(10) NOT NULL,
	SOLUONG INT NOT NULL,
	CONSTRAINT chk_slon CHECK(SOLUONG >= 0),
	GIATIEN MONEY NOT NULL,
	THANHTIEN MONEY NOT NULL,
	FOREIGN KEY (MAHOADON) REFERENCES HOADONONLINE(MAHOADON),
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
	CONSTRAINT PK_CTHOADONONLINE PRIMARY KEY (MAHOADON, MASP),
 )
 GO
 CREATE TABLE HOADONOFFLINE
 (
	MAHOADON VARCHAR(10) NOT NULL PRIMARY KEY,
	MAKH VARCHAR(10) NOT NULL,
	MACN VARCHAR(10) NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	NGAYLAP DATE NOT NULL,
	TONGTIEN MONEY default 0,
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
 )
 GO
 CREATE TABLE CTHOADONOFFLINE
 (
	MAHOADON VARCHAR(10) NOT NULL,
	MASP VARCHAR(10) NOT NULL,
	SOLUONG INT NOT NULL,
	CONSTRAINT chk_sloff CHECK(SOLUONG >= 0),
	GIATIEN MONEY NOT NULL,
	THANHTIEN MONEY NOT NULL,
	FOREIGN KEY (MAHOADON) REFERENCES HOADONOFFLINE(MAHOADON),
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
	CONSTRAINT PK_CTHOADONOFFLINE PRIMARY KEY (MAHOADON, MASP),
 )